### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by ASKabalan** [ASKabalan/jax-hpc-profiler#1]
- [x] add concat script as command 
- [x] add timer to generate proper CSVs
- [x] ~add a possibility to generate default parameters to JSON or YAML and read from it~
- [x] add a possibility to modify plot (dotted dashed colors) from YAML
- [x] filter input data size and GPUs if they are not present in data
- [x] add default plot titles and a possibility to change them with variables 
- [x] add a possibility to change plot names with variables 
- [x] Add possibilty to profile simple python (Non JAX) functions
- [x] Show what is required and what is not required in the README
- [x] Add ability to use seaborn context
- [x] ability to make transparent background

**Comment by ASKabalan** [comment]
- [x] Add an option to not log HLO, lowered code and memory analysis

**Comment by ASKabalan** [comment]
add some tests and badges

**Comment by ASKabalan** [comment]
Bump version and upload to PyPi
